# -*- coding: utf-8 -*-
"""LDR_fsim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAGQFZ5yKUSOoMXLXZhRLtxkIrI0b3NX
"""

from graphviz import Digraph

# Criação do gráfico de fluxograma com Graphviz
dot = Digraph(comment='Funcionamento de um LDR')

# Adicionando nós para o fluxograma
dot.node('A', 'Início', shape='ellipse')
dot.node('B', 'LDR Detecta Luz', shape='box')
dot.node('C', 'Alto Nível de Luz?', shape='diamond')
dot.node('D', 'Resistência Baixa', shape='box')
dot.node('E', 'Resistência Alta', shape='box')
dot.node('F', 'Saída do Circuito', shape='ellipse')
dot.node('G', 'Ação a ser relizada', shape='box')

# Adicionando as arestas (relações entre os nós)
dot.edge('A', 'B')
dot.edge('B', 'C')
dot.edge('C', 'D', label='Sim')
dot.edge('C', 'E', label='Não')
dot.edge('D', 'G')
dot.edge('E', 'G')
dot.edge('G', 'F')

# Renderizando o fluxograma
dot.render('fluxograma_ldr', format='png', cleanup=True)

# Exibindo o fluxograma gerado
from IPython.display import Image
Image('fluxograma_ldr.png')
