# -*- coding: utf-8 -*-
"""pir simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mAEEJ8CMNdxFN_7DQTEx3dee0J9VHx6
"""

from graphviz import Digraph

# Criação do gráfico de fluxograma com Graphviz
dot = Digraph(comment='Fluxograma do Programa PIR')

# Adicionando nós para o fluxograma
dot.node('A', 'Início', shape='ellipse')
dot.node('B', 'Recebe dados da entrada AD', shape='box')
dot.node('C', 'Loop Infinito', shape='diamond')
dot.node('D', 'Ler Nível de AD do Sensor PIR', shape='box')
dot.node('E', 'Presença Detectada?', shape='diamond')
dot.node('F', 'Presença detectada', shape='box')
dot.node('G', 'Presença não detectada', shape='box')
dot.node('H', 'Aguarda 3600 ms', shape='box')

# Adicionando as arestas (relações entre os nós)
dot.edge('A', 'B')
dot.edge('B', 'C')
dot.edge('C', 'D')
dot.edge('D', 'E')
dot.edge('E', 'F', label='Sim')
dot.edge('E', 'G', label='Não')
dot.edge('F', 'H')
dot.edge('G', 'H')
dot.edge('H', 'C')

# Renderizando o fluxograma
dot.render('fluxograma_programa_pir', format='png', cleanup=True)

# Exibindo o fluxograma gerado
from IPython.display import Image
Image('fluxograma_programa_pir.png')